build:
  version: "2.0"

accounts:
  message: "Welcome to YesBank accounts QA APIs"
  contactDetails:
    name: "Bahadur Shah - QA Manager"
    email: "shah@gmail.com"
  onCallSupport:
    - +(91) 987-1234-789
    - +(91) 987-1235-789
